version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9098:8000"  # map host port 9098 → container port 8000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9099:5173"  # map host port 9099 → Vite dev server port 5173
    volumes:
      - ./app:/app
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]
